pipeline:
  build-test-python:
    image: docker.twistbioscience-staging.com/devops_slave_python:3.8
    pull: true
    commands:
      - cd python
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - export PATH="$HOME/.poetry/bin:$PATH"
      - poetry install
      # - pip install invoke
      # - inv install
      - inv lint
      - inv test

  build-test-node:
    image: node:lts-alpine3.9
    pull: true
    commands:
      - cd node
      - npm install
      - npm run lint
      - npm run test

  build-test-ruby:
    image: docker.twistbioscience-staging.com/ecommerce_web:ruby-2.6.3
    pull: true
    commands:
      - cd ruby
      - gem install -g Gemfile
      - rubocop src tests *.rb
      - yardoc src/*
      - ruby -Ilib:test tests/tests.rb
    secrets: [ "nexus_pass"]