pipeline:
  build-test-python:
    image: docker.twistbioscience-staging.com/devops_slave_python:3.6
    pull: true
    commands:
      - bash
      - cd python
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - export PATH="$HOME/.poetry/bin:$PATH"
      - poetry install
      - poetry run invoke lint
      - poetry run invoke test
      - poetry version -s "0.1.$DRONE_BUILD_NUMBER"
      - poetry build -f sdist
      - poetry config "repositories.twist-configuration-client" "https://nexus.twistbioscience-staging.com/repository/pypi-hosted/" 
      - poetry env list
      - poetry config "http-basic.twist-configuration-client" $PY_PUBLISH_USER $PY_PUBLISH_PASSWORD
      - poetry env list
      - poetry publish -r twist -v
    secrets: [ py_publish_user, py_publish_password ]

  build-test-node:
    image: node:lts-alpine3.9
    pull: true
    commands:
      - cd node
      - npm install
      - npm run lint
      - npm run test

  build-test-ruby:
    image: docker.twistbioscience-staging.com/ecommerce_web:ruby-2.6.3
    pull: true
    commands:
      - cd ruby
      - gem install -g Gemfile
      - rubocop src tests *.rb
      - yardoc src/*
      - ruby -Ilib:test tests/tests.rb
    secrets: [ "nexus_pass"]